# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e69ccb09af87538b037da50766b4f61d9c5f3e220d30c97a8ee7b918f61873f07a9de5b14cf00a207ca519323b5736373a2157e807ce5b4a32241f45c523053a

test:
  secret_key_base: df1e5ccbf6dc3aee518b9536059a6a85c8fdfd9d8e2452f1c8914dcdaa69b03857f207c2da0b4927bd675bad2d0f9c71fdb63f419ec03be270d45a682a96abd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
